# Generated by Django 3.2.9 on 2023-08-10 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afishaslider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фотография *(1200x415)')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'название описание картинка',
                'verbose_name_plural': 'название описание картинка',
                'db_table': 'afisha',
            },
        ),
        migrations.CreateModel(
            name='Discountslider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=256, upload_to='', verbose_name='Фотография')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Баннер для Афиша',
                'verbose_name_plural': 'Баннер для Афиша',
                'db_table': 'discount',
            },
        ),
        migrations.CreateModel(
            name='Playbill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='apps/images/playbill', verbose_name='Фотография *(385x165)')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.CharField(max_length=16, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Афиша',
                'verbose_name_plural': 'Афиша',
                'db_table': 'playbill',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='apps/images/product', verbose_name='Фотография *(387x167)')),
                ('discounts', models.CharField(blank=True, max_length=16, null=True, verbose_name='Скидки')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('data', models.DateField(verbose_name='Дата')),
                ('price', models.CharField(max_length=16, verbose_name='Цена')),
                ('price_size', models.CharField(max_length=16, verbose_name='Цена со скидкой')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.service_category', verbose_name='Категория')),
                ('partners', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partners', verbose_name='Партнёр')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'product',
            },
        ),
    ]
