# Generated by Django 3.2.9 on 2023-07-06 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20230706_1528'),
        ('products', '0005_auto_20230704_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.service_category', verbose_name='Категория'),
        ),
    ]
