# Generated by Django 3.2.9 on 2023-07-12 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partners_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name': 'Партнёр', 'verbose_name_plural': 'Партнёр'},
        ),
    ]
