# Generated by Django 3.2.9 on 2023-08-10 09:17

import apps.categories.services
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[['XS', 'XS'], ['S', 'S'], ['M', 'M'], ['L', 'L'], ['XL', 'XL'], ['XXL', 'XXL']], default=None, max_length=100, null=True, verbose_name='Размер')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории для')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.categories.services.get_upload_path)),
                ('icon', models.FileField(blank=True, null=True, upload_to=apps.categories.services.get_upload_path, validators=[apps.categories.services.validate_file_extension])),
                ('is_main', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='categories.service_category')),
            ],
            options={
                'verbose_name': 'Категория Услуг',
                'verbose_name_plural': 'Категории Услуг',
                'db_table': 'service_category',
            },
        ),
        migrations.CreateModel(
            name='Sale_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории для')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.categories.services.get_upload_path)),
                ('icon', models.FileField(blank=True, null=True, upload_to=apps.categories.services.get_upload_path, validators=[apps.categories.services.validate_file_extension])),
                ('is_main', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='categories.sale_category')),
            ],
            options={
                'verbose_name': 'Категория Акции',
                'verbose_name_plural': 'Категории Акции',
                'db_table': 'sale_category',
            },
        ),
        migrations.CreateModel(
            name='Product_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории для')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.categories.services.get_upload_path)),
                ('icon', models.FileField(blank=True, null=True, upload_to=apps.categories.services.get_upload_path, validators=[apps.categories.services.validate_file_extension])),
                ('is_main', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='categories.product_category')),
            ],
            options={
                'verbose_name': 'Категория Товар',
                'verbose_name_plural': 'Категории Товар',
                'db_table': 'product_category',
            },
        ),
    ]
