# Generated by Django 3.2.9 on 2023-07-06 09:28

import apps.categories.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории для')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.categories.services.get_upload_path)),
                ('icon', models.FileField(blank=True, null=True, upload_to=apps.categories.services.get_upload_path, validators=[apps.categories.services.validate_file_extension])),
                ('is_main', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Категория Товар',
                'verbose_name_plural': 'Категории Товар',
                'db_table': 'product_category',
            },
        ),
        migrations.CreateModel(
            name='Sale_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории для')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.categories.services.get_upload_path)),
                ('icon', models.FileField(blank=True, null=True, upload_to=apps.categories.services.get_upload_path, validators=[apps.categories.services.validate_file_extension])),
                ('is_main', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Категория Акции',
                'verbose_name_plural': 'Категории Акции',
                'db_table': 'sale_category',
            },
        ),
        migrations.CreateModel(
            name='Service_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории для')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.categories.services.get_upload_path)),
                ('icon', models.FileField(blank=True, null=True, upload_to=apps.categories.services.get_upload_path, validators=[apps.categories.services.validate_file_extension])),
                ('is_main', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Категория услуг',
                'verbose_name_plural': 'Категории услуг',
                'db_table': 'service_category',
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
