# Generated by Django 3.2.9 on 2023-08-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_category',
            name='size',
        ),
        migrations.AlterField(
            model_name='service_category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название категории'),
        ),
    ]
