# Generated by Django 3.2.9 on 2023-07-07 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20230706_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service_category',
            options={'verbose_name': 'Категория Услуг', 'verbose_name_plural': 'Категории Услуг'},
        ),
        migrations.AlterField(
            model_name='service_category',
            name='parent',
            field=models.ForeignKey(blank=True, choices=[['XS', 'XS'], ['S', 'S'], ['M', 'M'], ['L', 'L'], ['XL', 'XL'], ['XXL', 'XXL']], default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='categories.service_category'),
        ),
    ]
