# Generated by Django 3.2.9 on 2023-07-07 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20230707_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_category',
            name='parent',
            field=models.ForeignKey(blank=True, choices=[['XS', 'XS'], ['S', 'S'], ['M', 'M'], ['L', 'L'], ['XL', 'XL'], ['XXL', 'XXL']], default=None, max_length=111, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='categories.service_category'),
        ),
    ]
