# Generated by Django 3.2.9 on 2023-07-07 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_service_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_category',
            name='size',
            field=models.CharField(blank=True, choices=[['XS', 'XS'], ['S', 'S'], ['M', 'M'], ['L', 'L'], ['XL', 'XL'], ['XXL', 'XXL']], default=None, max_length=100, null=True, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='service_category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='categories.service_category'),
        ),
    ]
