# Generated by Django 3.2.9 on 2023-08-23 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalinformation',
            options={'verbose_name': 'Доп. информация для характеристики ', 'verbose_name_plural': 'Доп. информации для характеристики'},
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristic',
            field=models.ManyToManyField(to='service.AdditionalInformation', verbose_name='Доп. инфо'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='service.ProductImage', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Партнер'),
        ),
    ]
