# Generated by Django 3.2.9 on 2023-08-28 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0003_auto_20230828_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=223, verbose_name='Название скидки или акции')),
                ('description', models.TextField(verbose_name='Условия и требования акции/скидки')),
                ('limitation', models.PositiveIntegerField(verbose_name='Ограничения по количеству')),
                ('start', models.DateField(verbose_name='Начало акции')),
                ('end', models.DateField(verbose_name='Конец акции')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Цена до скидки или акции')),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Цена со скидкой')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип скидки или акции',
                'verbose_name_plural': 'Тип скидки или акции:',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар/Услуга', 'verbose_name_plural': 'Товары/Услуги'},
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default=1, max_length=223, verbose_name='Название Товара/Услуги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Товар'), (2, 'Услуга')], default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceImage',
        ),
        migrations.AddField(
            model_name='promotion',
            name='promotion_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.promotiontype', verbose_name='Выберите тип скидки или акции'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Партнер'),
        ),
    ]
