# Generated by Django 3.2.9 on 2023-08-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20230828_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name': 'Акция/Скидка', 'verbose_name_plural': 'Акции/Скидки'},
        ),
        migrations.AddField(
            model_name='promotion',
            name='cashback_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Количество кэшбека'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='percentage_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Количество процента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(to='service.Product', verbose_name='Выберите товар/услугу для акций и скидки'),
        ),
    ]
