# Generated by Django 3.2.9 on 2023-07-12 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_contacts_email_e'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='email_e',
        ),
    ]
