# Generated by Django 3.2.9 on 2023-08-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicuser',
            options={'verbose_name': 'Обычный пользователь', 'verbose_name_plural': 'Обычные пользователи'},
        ),
        migrations.RemoveField(
            model_name='basicuser',
            name='surname',
        ),
    ]
