# Generated by Django 3.2.9 on 2023-08-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230814_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicuser',
            old_name='phone_one',
            new_name='phone_number',
        ),
    ]
