# Generated by Django 3.2.9 on 2023-08-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_phone_one_basicuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='activity_type',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Тип деятельности'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=None, max_length=500, unique=True, verbose_name='Почта'),
        ),
    ]
