# Generated by Django 3.2.9 on 2023-08-23 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230822_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicuser',
            name='card',
        ),
    ]
