# Generated by Django 3.2.9 on 2023-07-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=32, verbose_name=' Введите адрес электронной почты')),
                ('number', models.CharField(max_length=16, verbose_name='Телефон')),
                ('num_card', models.CharField(max_length=36, verbose_name='Номер карты')),
                ('surname', models.CharField(max_length=16, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=16, verbose_name='Имя')),
                ('password', models.CharField(max_length=36, verbose_name='Придумайте пароль')),
                ('password_rep', models.CharField(max_length=36, verbose_name='Повторите пароль')),
            ],
            options={
                'verbose_name': 'Регистрация пользователя',
                'verbose_name_plural': 'Регистрация пользователя',
                'db_table': 'Регистрация',
            },
        ),
    ]
