# Generated by Django 3.2.9 on 2023-07-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='mau',
            field=models.SlugField(default=1, max_length=122, verbose_name=' xse'),
            preserve_default=False,
        ),
    ]
