# Generated by Django 3.2.9 on 2023-07-13 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_register_mau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='mau',
        ),
    ]
